name: agent

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  agent_data:
    path: ../../data/agent_data
  core:
    path: ../../core
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.3.0

flutter:
  uses-material-design: true

