name: agent_domain

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  core:
    path: ../../core
  shared_dependency:
    path: ../../shared_dependency

dev_dependencies:
  flutter_test:
    sdk: flutter

