include: strict_lint.yaml

analyzer:
  exclude:
    - '**/app_localizations*.dart'
    - '**.g.dart'
    - '**.freezed.dart'
#    - '**/coverage_test.dart'
  errors:
    invalid_annotation_target: ignore # https://github.com/rrousselGit/freezed/issues/488

linter:
  rules:
    # Follow flutter repo https://github.com/flutter/flutter/blob/master/analysis_options.yaml
    prefer_single_quotes: true
    sort_constructors_first: true