include: strict_lint.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - '**/app_localizations**.dart'
    - '**.g.dart'
    - '**.freezed.dart'
  errors:
    invalid_annotation_target: ignore # https://github.com/rrousselGit/freezed/issues/488

linter:
  rules:
    # Follow flutter repo https://github.com/flutter/flutter/blob/master/analysis_options.yaml
    prefer_single_quotes: true
    sort_constructors_first: true

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else