targets:
  $default:
    sources:
      include:
        - "**"
      exclude:
        - ".dart_tool/**"
        - "**/.dart_tool/**"
        - "**.freezed.dart"
        - "**.g.dart"
        - "app_localizations*.dart"