name: shared_dependency

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_secure_storage: ^7.0.1
  freezed_annotation: ^2.2.0
  go_router: ^5.2.4
  shared_preferences: ^2.0.15
