name: auth

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  auth_data:
    path: ../../data/auth_data
  core:
    path: ../../core
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
